name: EzMiner
version: '${project.version}'
main: me.ezplugin.EzMiner
api-version: 1.18
authors: [ EzCoins ]
description: Made by EzCoins
depend:
commands:
  EzMiner:
    description: Opens the forge
    usage: /<command>
